name: Quiz-Manager Production Deployment

env:
    VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
    VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
    push:
        branches:
            - main

jobs:

    Build-Production:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Install Vercel CLI
              run: npm install --global vercel

            - name: Pull Vercel Environment Information
              run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

            - name: Build Project Artifacts
              run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}


    Test:
        needs: [Build-Production]
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - uses: actions/checkout@v3
              with:
                node-version: 18

            - name: Install dependencies
              run: npm install --no-fund --ignore-scripts --prefix

            - run: npm ci

            - name: Run tests
              run: npm run test:prod --prefix react-quiz-backend

            # - name: Run tests
            #   run: npm run test --no-fund --ignore-scripts --prefix


    Deploy-Production:
        needs: [Test]
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            # - name: Install Vercel CLI
            #   run: npm install --global vercel

            # - name: Pull Vercel Environment Information
            #   run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

            # - name: Build Project Artifacts
            #   run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

            - name: Deploy Project Artifacts
              run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}

